# Generated by Django 2.2.13 on 2020-10-16 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField()),
                ('total', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('articulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Articulo')),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='articulos',
            field=models.ManyToManyField(related_name='articulo', through='api.Pedido_detalle', to='api.Articulo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cliente'),
        ),
    ]
